### ISSUE TITLE
Scroll on quizzes

### ISSUE THREAD

**Issue by sylvia-sable** [theirc/coach-erevu#150]
It would be ideal to be able to hold the app horizontally and vertically. 

When I hold it horizontally and try to scroll through the quiz, the answers meld together.

See video: https://photos.app.goo.gl/55wGQxsrjvot1oN39 

**Possible to fix?** If not, I can set the tablet orientation to stay vertical.

**Comment by secretrobotron** [comment]
Any thoughts, @ryanwarsaw? Can we reload the activity or something?

**Comment by ryanwarsaw** [comment]
I'm working on fixing it now, just a heads up.

**Comment by ryanwarsaw** [comment]
Fixed in #171 this bug is no longer possible under the current implementation. For the record, it was caused when `onCreate` would be triggered after an orientation change. To fix this I added some flags to let Android automatically handle orientation changes, and also instead of depending on a flag to determine the logic to either `add` or `replace` a fragment, we just always replace the fragment even if a previous one doesn't exist. The end result means even if another edge case pops up, it won't be visible to the user.
