### ISSUE TITLE
create coach erevu edition 1 and edition 2 

### ISSUE THREAD

**Issue by lauradereynal** [theirc/coach-erevu#67]

**Comment by secretrobotron** [comment]
@lauradereynal what do you have in mind here? Are you looking for a way to distinguish the old app from the one we're working on now? Or are you looking to make 2 different apps at the same time here? Either way is fine 🎉 . If it's the latter, @ryanwarsaw and I can figure out how to store two versions of content in the same repo (or something else more useful).

**Comment by lauradereynal** [comment]
@secretrobotron thanks for checking. This was originally thought as a solution to a large number of files and content. But now it's obsolete. We will work on 3 months of content for now and not 6. so I think we can hold everything inside 1 app. Correct? 

We were basically thinking with @ryanwarsaw that if we had 30 videos, we would need to make 2 apps of 15 videos each in order to hold everything because we won't be able to update the app dynamically. 


Thoughts ?

**Comment by ryanwarsaw** [comment]
@lauradereynal We can do that, with varying difficulty depending on if you want both installed at the same time, or two separate apps that you can install and switch between. Both of these are very feasible, it just requires some changes so that Android will tolerate it properly. 

Also, not sure if we need this feature; if you wanted to just put all 30 videos into the single APK that works totally fine - alternatively we can just put the 3 months, and you can put the rest in the downloads folder (not packaged) in the future. Either way you want to do it, it's totally up to you.

**Comment by lauradereynal** [comment]
for now, the priority is to make the app ready for 13 videos, not 30. So we are fine for this round I think. Correct @ryanwarsaw ? 

Can we have one single app that holds 13 videos ? 

I hope there is enough space on our tablets.

**Comment by ryanwarsaw** [comment]
@lauradereynal We can have an app that holds 13 videos, it's a matter of whether or not there is enough space on the tablet for that amount of videos. If you have information on the storage size of the device, and how much free space there is I can give you a pretty good estimation on whether or not that'll be an issue for us or not.

**Comment by lauradereynal** [comment]
closing this until we have this problem again.
